<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116143650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE carte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(100) NOT NULL, description VARCHAR(150) NOT NULL, cout_pd SMALLINT DEFAULT NULL, gain_argent SMALLINT DEFAULT NULL, effet VARCHAR(200) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BAD4FFFD6C6E55B5 ON carte (nom)');
        $this->addSql('CREATE TABLE carte_partie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, emplacement VARCHAR(20) NOT NULL, partie_id INT NOT NULL, joueur_id INT DEFAULT NULL, carte_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_137F7F0CE075F7A4 ON carte_partie (partie_id)');
        $this->addSql('CREATE INDEX IDX_137F7F0CA9E2D76C ON carte_partie (joueur_id)');
        $this->addSql('CREATE INDEX IDX_137F7F0CC9C7CEB6 ON carte_partie (carte_id)');
        $this->addSql('CREATE TABLE joueur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, argent SMALLINT NOT NULL, ordre_jeu SMALLINT DEFAULT NULL, partie_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD71A9C5E075F7A4 ON joueur (partie_id)');
        $this->addSql('CREATE INDEX IDX_FD71A9C5FB88E14F ON joueur (utilisateur_id)');
        $this->addSql('CREATE TABLE projet_en_cours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, avancement_pd SMALLINT DEFAULT NULL, est_bloque BOOLEAN DEFAULT NULL, modificateurs_json VARCHAR(100) DEFAULT NULL, carte_partie_id INT NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C710EC5A74635D3 ON projet_en_cours (carte_partie_id)');
        $this->addSql('CREATE INDEX IDX_C710EC5AA9E2D76C ON projet_en_cours (joueur_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(100) NOT NULL, mot_de_passe VARCHAR(255) NOT NULL, pseudo VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, partie_active_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B386CC499D ON utilisateur (pseudo)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3A4F920F2 ON utilisateur (partie_active_id)');
        $this->addSql('ALTER TABLE carte_partie ADD CONSTRAINT FK_137F7F0CE075F7A4 FOREIGN KEY (partie_id) REFERENCES partie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE carte_partie ADD CONSTRAINT FK_137F7F0CA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id)');
        $this->addSql('ALTER TABLE carte_partie ADD CONSTRAINT FK_137F7F0CC9C7CEB6 FOREIGN KEY (carte_id) REFERENCES carte (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE joueur ADD CONSTRAINT FK_FD71A9C5E075F7A4 FOREIGN KEY (partie_id) REFERENCES partie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE joueur ADD CONSTRAINT FK_FD71A9C5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE projet_en_cours ADD CONSTRAINT FK_C710EC5A74635D3 FOREIGN KEY (carte_partie_id) REFERENCES carte_partie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projet_en_cours ADD CONSTRAINT FK_C710EC5AA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3A4F920F2 FOREIGN KEY (partie_active_id) REFERENCES partie (id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_joueur_user_partie ON joueur (utilisateur_id, partie_id);
');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carte_partie DROP CONSTRAINT FK_137F7F0CE075F7A4');
        $this->addSql('ALTER TABLE carte_partie DROP CONSTRAINT FK_137F7F0CA9E2D76C');
        $this->addSql('ALTER TABLE carte_partie DROP CONSTRAINT FK_137F7F0CC9C7CEB6');
        $this->addSql('ALTER TABLE joueur DROP CONSTRAINT FK_FD71A9C5E075F7A4');
        $this->addSql('ALTER TABLE joueur DROP CONSTRAINT FK_FD71A9C5FB88E14F');
        $this->addSql('ALTER TABLE projet_en_cours DROP CONSTRAINT FK_C710EC5A74635D3');
        $this->addSql('ALTER TABLE projet_en_cours DROP CONSTRAINT FK_C710EC5AA9E2D76C');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3A4F920F2');
        $this->addSql('DROP TABLE carte');
        $this->addSql('DROP TABLE carte_partie');
        $this->addSql('DROP TABLE joueur');
        $this->addSql('DROP TABLE projet_en_cours');
        $this->addSql('DROP TABLE utilisateur');
    }
}
